version: "1"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - server-ktor
    restart: always
    volumes:
      - ./etc/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro

  certbot:
    image: certbot/certbot:latest
    restart: always
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  server-ktor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:80"
    restart: always
    networks:
      - example-network

  netwroks:
    example-network