version: "1"
services:
  sosialpedia_ktor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - /opt/sosialpedia/app:/app
    environment:
      - DB_USERNAME=reno
      - DB_PASSWORD=shalom7007

    restart: always