@startuml
entity User {
 * id : VARCHAR(50)
 --
 * username : VARCHAR(50)
 email : VARCHAR(100)
 * hashed_password : VARCHAR(100)
 * salt : VARCHAR(100)
 phone_number : VARCHAR(50)
 profile_pic : VARCHAR(100)
 bio : TEXT
 date_birth : BIGINT
 * created_at : BIGINT
 updated_at : BIGINT
 last_login : BIGINT
 ip_address : VARCHAR(45)
 device : VARCHAR(150)
 gender : GENDER
}

entity Post {
* id : VARCHAR(50)
--
* user_id : VARCHAR(50)
* content : TEXT
have_attachment : Boolean
* created_at : BIGINT
}

entity Comment {
* id : VARCHAR(50)
--
* user_id : VARCHAR(50)
* post_id : VARCHAR(50)
* content : TEXT
have_attachment : Boolean
* created_at : BIGINT
}

entity ChildComment {
* id : VARCHAR(50)
--
* user_id : VARCHAR(50)
* post_id : VARCHAR(50)
* comment_id : VARCHAR(50)
* content : TEXT
have_attachment : Boolean
* created_at : BIGINT
}

entity Like {
* id : VARCHAR(50)
--
* user_id : VARCHAR(50)
post_id : VARCHAR(50)
comment_id : VARCHAR(50)
}

entity Dislike {
* id : VARCHAR(50)
--
* user_id : VARCHAR(50)
post_id : VARCHAR(50)
comment_id : VARCHAR(50)
}

User --{ Post
User --{ Comment
User --{ ChildComment
User --{ Like
User --{ Dislike
Post --{ Comment
Post --{ ChildComment
Post --{ Like
Post --{ Dislike
Comment --{ ChildComment
Comment --{ Like
Comment --{ Dislike
@enduml
